(() => {
  "use strict";
  const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
  const cfg={url:String(window.MATHSERA_SUPABASE_URL||"").replace(/\/$/,""),key:String(window.MATHSERA_SUPABASE_PUBLISHABLE_KEY||"")},id=new URLSearchParams(location.search).get("id");let R=null,imgs=[],idx=0;
  function parse(data){let b={};try{const x=JSON.parse(data.body||"");if(x&&typeof x==="object")b=x}catch(e){}const t=b.taxonomy&&typeof b.taxonomy==="object"?b.taxonomy:{};const pages=Array.isArray(b.pages)?b.pages.filter(x=>x&&x.url).sort((a,b)=>Number(a.page||0)-Number(b.page||0)):[];const images=pages.length?pages.map(x=>x.url):(Array.isArray(b.images)?b.images.filter(Boolean):(data.image_url?[data.image_url]:[]));return {...data,b,examCategory:t.examCategory||data.category||"",examName:t.examName||b.examName||"",classLevel:t.classLevel||data.class_name||"",board:t.board||data.board||"",subject:t.subject||data.subject||"",publication:t.publication||b.publication||"",chapter:t.chapter||data.chapter||"",exercise:t.exercise||data.exercise||"",type:t.materialType||data.content_type||"Resource",year:t.year||b.examYear||"",language:t.language||b.language||"",explanation:b.explanation||"",images,pdf:b.pdf||data.pdf_url||""}}
  function groupKey(){return [R.examCategory,R.examName,R.board,R.classLevel].map(x=>String(x||"").trim().toLowerCase()).join("|")}
  function libraryHash(){const p=new URLSearchParams();p.set("library","type");if(R.examName)p.set("exam",R.examName);p.set("group",groupKey());if(R.subject)p.set("subject",R.subject);if(R.type)p.set("type",R.type);if(R.publication)p.set("publication",R.publication);return"#"+p.toString()}
  function fileName(name,ext){return String(name||"mathsera-resource").replace(/[^a-z0-9._-]+/gi,"-").slice(0,90)+(ext||"")}
  function ext(url){const p=String(url||"").split("?")[0].toLowerCase();return p.endsWith(".png")?".png":p.endsWith(".webp")?".webp":".jpg"}
  async function download(url,name){try{const res=await fetch(url);if(!res.ok)throw new Error();const blob=await res.blob();const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}catch(e){window.open(url,"_blank","noopener")}}
  async function downloadAll(){if(!window.JSZip){alert("Download-all support unavailable.");return}const btn=$("downloadAll");btn.disabled=true;btn.textContent="Preparing ZIP…";try{const z=new JSZip();for(let i=0;i<imgs.length;i++){const res=await fetch(imgs[i]);if(!res.ok)throw new Error(`Page ${i+1} failed`);z.file(fileName(`${R.title}-page-${i+1}`,ext(imgs[i])),await res.blob())}const blob=await z.generateAsync({type:"blob"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=fileName(R.title,".zip");document.body.appendChild(a);a.click();a.remove()}catch(e){alert(e.message||"Could not prepare ZIP.")}finally{btn.disabled=false;btn.textContent="⬇ Download All Images"}}
  function gallery(){if(!imgs.length)return"";return `<section class="box"><h2>Pages / Images</h2><img id="mainImage" class="gallery-main" src="${esc(imgs[0])}" alt="${esc(R.title)} — Page 1"><div class="gallery-nav"><button id="prevPage" type="button">← Previous</button><b id="pageCount">Page 1 of ${imgs.length}</b><button id="nextPage" type="button">Next →</button></div><div class="thumbs">${imgs.map((u,i)=>`<button type="button" class="thumb ${i===0?"active":""}" data-page="${i}"><img src="${esc(u)}" alt="Page ${i+1}"></button>`).join("")}</div><div class="actions"><button id="downloadCurrent" class="download-btn primary" type="button">⬇ Download Current Image</button><button id="downloadAll" class="download-btn" type="button">⬇ Download All Images</button>${R.pdf?`<button id="downloadPdf" class="download-btn primary" type="button">⬇ Download PDF</button><a class="download-btn" href="${esc(R.pdf)}" target="_blank" rel="noopener">📄 Open PDF</a>`:""}</div></section>`}
  function update(){if(!imgs.length)return;$("mainImage").src=imgs[idx];$("pageCount").textContent=`Page ${idx+1} of ${imgs.length}`;$("prevPage").disabled=idx===0;$("nextPage").disabled=idx===imgs.length-1;$("downloadCurrent").onclick=()=>download(imgs[idx],fileName(`${R.title}-page-${idx+1}`,ext(imgs[idx])));document.querySelectorAll(".thumb").forEach((b,i)=>{b.classList.toggle("active",i===idx);if(i===idx)b.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})})}
  function openModal(){$("modalImage").src=imgs[idx];$("modalCaption").textContent=`${R.title} • Page ${idx+1} of ${imgs.length}`;$('imageModal').classList.add("open");document.body.style.overflow="hidden"}function closeModal(){$('imageModal').classList.remove("open");$('modalImage').src="";document.body.style.overflow=""}
  function render(){const tags=[R.examName,R.board,R.classLevel?`Class ${R.classLevel}`:"",R.subject,R.publication,R.chapter,R.exercise,R.year,R.language].filter(Boolean).map(x=>`<span class="tag">${esc(x)}</span>`).join("");const crumb=[R.examName,R.board,R.classLevel?`Class ${R.classLevel}`:"",R.subject,R.publication,R.chapter,R.exercise].filter(Boolean).map(esc).join(" › ");$('app').innerHTML=`<div class="crumb">${crumb}</div><header class="hero"><div class="type">${esc(R.type)}</div><h1>${esc(R.title||"MathsEra Resource")}</h1><div class="tags">${tags}</div></header>${R.explanation?`<section class="box"><h2>Explanation / Notes</h2><div class="explanation">${esc(R.explanation)}</div></section>`:""}${gallery()}`;document.title=`${R.title||"MathsEra Resource"} | MathsEra Classes`;$('metaDescription').content=`${R.title||"MathsEra learning resource"} — ${R.classLevel} ${R.board} ${R.chapter}`.trim();$('canonicalLink').href=location.href;$('libraryLink').href=`library.html${libraryHash()}`;if(imgs.length){$('prevPage').onclick=()=>{if(idx>0){idx--;update()}};$('nextPage').onclick=()=>{if(idx<imgs.length-1){idx++;update()}};document.querySelectorAll('.thumb').forEach(b=>b.onclick=()=>{idx=Number(b.dataset.page);update()});$('mainImage').onclick=openModal;$('downloadAll').onclick=downloadAll;if(R.pdf)$('downloadPdf').onclick=()=>download(R.pdf,fileName(R.title,'.pdf'));update();let sx=0,sy=0;$('mainImage').addEventListener('touchstart',e=>{sx=e.changedTouches[0].clientX;sy=e.changedTouches[0].clientY},{passive:true});$('mainImage').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.2){if(dx<0&&idx<imgs.length-1)idx++;if(dx>0&&idx>0)idx--;update()}},{passive:true})}}
  $('modalClose').onclick=closeModal;$('imageModal').onclick=e=>{if(e.target===$('imageModal'))closeModal()};$('backBtn').onclick=()=>{if(history.length>1&&document.referrer&&new URL(document.referrer).origin===location.origin)history.back();else location.href=$('libraryLink').href};$('shareBtn').onclick=async()=>{try{if(navigator.share)await navigator.share({title:document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);$('shareBtn').textContent='✓ Link Copied';setTimeout(()=>$('shareBtn').textContent='↗ Share',1500)}}catch(e){}};
  async function related(){try{const u=new URL(cfg.url+"/rest/v1/resources");u.searchParams.set("select","id,title,content_type,chapter,exercise,image_url,body");u.searchParams.set("published","eq.true");u.searchParams.set("subject","eq."+R.subject);u.searchParams.set("limit","6");const q=await fetch(u,{headers:{apikey:cfg.key,Authorization:"Bearer "+cfg.key}});if(!q.ok)return;const rows=await q.json();const filtered=rows.filter(x=>String(x.id)!==String(R.id)).slice(0,4);if(!filtered.length)return;$('related').hidden=false;$('relatedGrid').innerHTML=filtered.map(x=>`<a class="related-card" href="resource.html?id=${encodeURIComponent(x.id)}"><b>${esc(x.title)}</b><small>${esc(x.content_type||"Resource")}${x.chapter?` • ${esc(x.chapter)}`:""}${x.exercise?` • ${esc(x.exercise)}`:""}</small></a>`).join('')}catch(e){}}
  async function load(){try{if(!id)throw new Error("Resource ID missing.");if(!cfg.url||!cfg.key)throw new Error("Supabase configuration missing.");const u=new URL(cfg.url+"/rest/v1/resources");u.searchParams.set("select","*");u.searchParams.set("id","eq."+id);u.searchParams.set("published","eq.true");u.searchParams.set("limit","1");const q=await fetch(u,{headers:{apikey:cfg.key,Authorization:"Bearer "+cfg.key}});if(!q.ok)throw new Error(`Database request failed (HTTP ${q.status}).`);const rows=await q.json();if(!rows.length)throw new Error("Published resource not found.");R=parse(rows[0]);imgs=R.images;render();related()}catch(e){$('app').innerHTML=`<div class="error"><h2>Resource could not be loaded</h2><p>${esc(e.message||e)}</p></div>`}}
  load();
})();
