-- MathsEra Classes: starter database for the new website
create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  class_name text,
  board text,
  subject text,
  chapter text,
  exercise text,
  question_number text,
  content_type text,
  body text,
  image_url text,
  pdf_url text,
  video_url text,
  published boolean default false,
  created_at timestamptz default now()
);

alter table public.resources enable row level security;

create policy "Public can read published resources"
on public.resources for select
using (published = true);

create policy "Authenticated users can insert resources"
on public.resources for insert
to authenticated
with check (true);

-- Later, replace the broad insert policy with an admin-only policy
-- after the admin role/profile system is finalized.
