-- ============================================================
-- MathsEra Classes — Universal Learning Library + Solution Portal
-- Safe migration for the existing `public.resources` table.
-- Run this whole file once in Supabase SQL Editor.
-- ============================================================

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  class_name text,
  board text,
  subject text,
  publication text,
  chapter text,
  exercise text,
  question_number text,
  content_type text,
  body text,
  image_url text,
  pdf_url text,
  video_url text,
  published boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Add missing columns without destroying existing content.
alter table public.resources add column if not exists publication text;
alter table public.resources add column if not exists updated_at timestamptz default now();

-- Keep existing rows compatible with the new taxonomy.
update public.resources
set updated_at = coalesce(updated_at, created_at, now())
where updated_at is null;

create index if not exists resources_published_created_idx
  on public.resources (published, created_at desc);
create index if not exists resources_library_path_idx
  on public.resources (category, class_name, board, subject, chapter, exercise, content_type);
create index if not exists resources_publication_idx
  on public.resources (publication);

alter table public.resources enable row level security;

drop policy if exists "Public can read published resources" on public.resources;
create policy "Public can read published resources"
on public.resources for select
to anon, authenticated
using (published = true);

drop policy if exists "Authenticated users can insert resources" on public.resources;
create policy "Authenticated users can insert resources"
on public.resources for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update resources" on public.resources;
create policy "Authenticated users can update resources"
on public.resources for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete resources" on public.resources;
create policy "Authenticated users can delete resources"
on public.resources for delete
to authenticated
using (true);

-- ============================================================
-- Storage bucket for solution images / PDFs
-- ============================================================
insert into storage.buckets (id, name, public)
values ('library-files', 'library-files', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can read MathsEra library files" on storage.objects;
create policy "Public can read MathsEra library files"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'library-files');

drop policy if exists "Authenticated can upload MathsEra library files" on storage.objects;
create policy "Authenticated can upload MathsEra library files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'library-files');

drop policy if exists "Authenticated can update MathsEra library files" on storage.objects;
create policy "Authenticated can update MathsEra library files"
on storage.objects for update
to authenticated
using (bucket_id = 'library-files')
with check (bucket_id = 'library-files');

drop policy if exists "Authenticated can delete MathsEra library files" on storage.objects;
create policy "Authenticated can delete MathsEra library files"
on storage.objects for delete
to authenticated
using (bucket_id = 'library-files');

-- ============================================================
-- Optional automatic updated_at trigger
-- ============================================================
create or replace function public.mathsera_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists mathsera_resources_updated_at on public.resources;
create trigger mathsera_resources_updated_at
before update on public.resources
for each row execute function public.mathsera_set_updated_at();

-- ============================================================
-- IMPORTANT
-- The website stores the canonical taxonomy inside `body` as JSON.
-- Publication is also mirrored to the `publication` column when the
-- column exists. This keeps the site compatible with older records.
-- ============================================================
