-- ============================================================
-- MathsEra Classes V10 — Professional Educational CMS
-- IMPORTANT: run this in Supabase SQL Editor after the existing schema.
-- 1) Create the tables.
-- 2) Create ONE admin profile for your own Supabase Auth user UUID.
-- 3) Do not expose service-role keys in the website.
-- ============================================================

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  is_admin boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null, class_name text, subject text, board text,
  description text, duration text, whatsapp_url text,
  published boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.batches (
  id bigint generated by default as identity primary key,
  title text not null, class_name text, subject text, board text,
  start_date text, timing text, duration text, fee text, status text,
  description text, published boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.fees (
  id bigint generated by default as identity primary key,
  title text not null, course text, amount text, duration text,
  payment_note text, description text, published boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  student_name text not null, class_name text, exam text, marks text,
  percentage text, rank text, achievement text, year text, photo_url text,
  published boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null, description text, event_date text, event_time text,
  venue text, eligibility text, registration_fee text, registration_url text,
  prizes text, rules text, status text, poster_url text,
  published boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null, type text, body text, publish_date text,
  published boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.posters (
  id bigint generated by default as identity primary key,
  title text not null, description text, image_url text,
  button_text text, button_url text,
  published boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  caption text, category text, image_url text,
  published boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

-- Helper: only your own admin profile can write.
create or replace function public.mathsera_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_profiles
    where user_id = auth.uid() and is_admin = true
  );
$$;

-- Public users can ONLY read published records.
-- Admins can read/write all records.
do $$
declare t text;
begin
  foreach t in array array['courses','batches','fees','achievements','events','announcements','posters','gallery']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "Public read published" on public.%I', t);
    execute format('create policy "Public read published" on public.%I for select to anon, authenticated using (published = true)', t);
    execute format('drop policy if exists "Admin read all" on public.%I', t);
    execute format('create policy "Admin read all" on public.%I for select to authenticated using (public.mathsera_is_admin())', t);
    execute format('drop policy if exists "Admin insert" on public.%I', t);
    execute format('create policy "Admin insert" on public.%I for insert to authenticated with check (public.mathsera_is_admin())', t);
    execute format('drop policy if exists "Admin update" on public.%I', t);
    execute format('create policy "Admin update" on public.%I for update to authenticated using (public.mathsera_is_admin()) with check (public.mathsera_is_admin())', t);
    execute format('drop policy if exists "Admin delete" on public.%I', t);
    execute format('create policy "Admin delete" on public.%I for delete to authenticated using (public.mathsera_is_admin())', t);
  end loop;
end $$;

alter table public.admin_profiles enable row level security;
drop policy if exists "Admin can read own profile" on public.admin_profiles;
create policy "Admin can read own profile" on public.admin_profiles
for select to authenticated using (user_id = auth.uid());

-- Tighten the existing resources table: replace broad authenticated write policies.
alter table public.resources enable row level security;
drop policy if exists "Authenticated users can insert resources" on public.resources;
drop policy if exists "Authenticated users can update resources" on public.resources;
drop policy if exists "Authenticated users can delete resources" on public.resources;

drop policy if exists "Only admin can insert resources" on public.resources;
create policy "Only admin can insert resources" on public.resources
for insert to authenticated with check (public.mathsera_is_admin());
drop policy if exists "Only admin can update resources" on public.resources;
create policy "Only admin can update resources" on public.resources
for update to authenticated using (public.mathsera_is_admin()) with check (public.mathsera_is_admin());
drop policy if exists "Only admin can delete resources" on public.resources;
create policy "Only admin can delete resources" on public.resources
for delete to authenticated using (public.mathsera_is_admin());

-- Storage: only admin can write; public can read.
drop policy if exists "Authenticated can upload MathsEra library files" on storage.objects;
drop policy if exists "Authenticated can update MathsEra library files" on storage.objects;
drop policy if exists "Authenticated can delete MathsEra library files" on storage.objects;
drop policy if exists "Only admin can upload MathsEra library files" on storage.objects;
create policy "Only admin can upload MathsEra library files"
on storage.objects for insert to authenticated
with check (bucket_id = 'library-files' and public.mathsera_is_admin());
drop policy if exists "Only admin can update MathsEra library files" on storage.objects;
create policy "Only admin can update MathsEra library files"
on storage.objects for update to authenticated
using (bucket_id = 'library-files' and public.mathsera_is_admin())
with check (bucket_id = 'library-files' and public.mathsera_is_admin());
drop policy if exists "Only admin can delete MathsEra library files" on storage.objects;
create policy "Only admin can delete MathsEra library files"
on storage.objects for delete to authenticated
using (bucket_id = 'library-files' and public.mathsera_is_admin());

-- Optional: one updated_at trigger for every CMS table.
create or replace function public.mathsera_cms_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

do $$
declare t text;
begin
  foreach t in array array['courses','batches','fees','achievements','events','announcements','posters','gallery']
  loop
    execute format('drop trigger if exists mathsera_%I_updated_at on public.%I', t, t);
    execute format('create trigger mathsera_%I_updated_at before update on public.%I for each row execute function public.mathsera_cms_updated_at()', t, t);
  end loop;
end $$;

-- AFTER creating your Supabase Auth user, run this once with YOUR user UUID:
-- insert into public.admin_profiles(user_id,display_name,is_admin)
-- values ('YOUR-AUTH-USER-UUID','Praveen Sir',true)
-- on conflict (user_id) do update set is_admin=true, display_name=excluded.display_name;
